config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :clients
  devise_for :administrators
  resources :administrators, only: %i[new create destroy show edit update]
  resources :clients, only: %i[new create destroy show edit update]
  resources :bills, only: %i[show create]
  resources :apartments
  resources :requests
  resources :hotels
  resources :users
  root to: 'apartments#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/request.rb
class Request < ApplicationRecord
  before_create :set_residence_time

  enum apartment_class: %i[A B C Luxe]
  enum status: %i[pending in_progress approved canceled]
  belongs_to :user
  has_one :bill

  validate :check_residence_time
  validates :number_of_beds, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :check_in_date, presence: true # , format: { with: /\A\d{0,4}-\d{0,2}-\d{0,2} \d{0,2}:\d{0,2}\z/i }
  validates :eviction_date, presence: true # , format: { with: /\A\d{0,4}-\d{0,2}-\d{0,2} \d{0,2}:\d{0,2}\z/i }

  def apartment_class=(value)
    super
  rescue ArgumentError
    @attributes.write_cast_value('apartment_class', value)
  end

  def status=(value)
    super
  rescue ArgumentError
    @attributes.write_cast_value('status', value)
  end

  private

  def check_residence_time
    return if eviction_date.nil? || check_in_date.nil?
    return unless (eviction_date - check_in_date) / 86_400 < 1

    errors.add(:residence_time, 'incorrect period')
  end

  def set_residence_time
    self.residence_time = ActiveSupport::Duration.build(eviction_date - check_in_date).iso8601
  end


end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  include RequestsHelper
  before_action :set_request, only: %i[ show edit update destroy ]

  # GET /requests or /requests.json
  def index
    @requests = filter_by_params(Request.all, filter_params)
    @requests = sort_by_params(@requests, sort_params)
  end

  # GET /requests/1 or /requests/1.json
  def show; end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit; end

  # POST /requests or /requests.json
  def create
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to request_url(@request), notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1 or /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to request_url(@request), notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1 or /requests/1.json
  def destroy
    respond_to do |format|
      if @request.destroy
        format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to requests_url, notice: 'Something go wrong.' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_request
    @request = Request.find(params[:id])
  end

  def filter_params
    params.fetch(:filter, {}).permit(apartment_class: [], status: [])
  end

  def sort_params
    params.fetch(:sort, {}).permit(:apartment_class, :status)
  end

    # Only allow a list of trusted parameters through.
  def request_params
    params.require(:request).permit(:client_id, :apartment_class, :number_of_beds, :eviction_date, :check_in_date, :status)
    params[:request][:status] = :pending if current_user.role != :admin
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
  def filter_by_params(scope, params)
    params.each do |key, value|
      next if value.blank?

      scope = case key.to_s
              when 'apartment_class'
                scope.where(apartment_class: value)
              when 'status'
                scope.where(status: value)
              else
                scope
              end
    end
    scope
  end

  def sort_by_params(scope, params)
    params.each do |key, value|
      next unless %w[desc asc].include?(value)

      scope = case key.to_s
              when 'apartment_class'
                scope.order("apartment_class #{value}")
              when 'status'
                scope.order("status #{value}")
              else
                scope
              end
    end
    scope
  end
end

app/views/requests/_form.html.erb
<%= form_with(model: request) do |form| %>
  <% if request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
        <% request.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Requests</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.id %></td>
        <td><%= request.residence_time %></td>
        <td><%= request.apartment_class %></td>
        <td><%= request.status %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>