config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :clients
  devise_for :administrators
  resources :administrators, only: %i[new create destroy show edit update]
  resources :clients, only: %i[new create destroy show edit update]
  resources :bills, only: %i[show create]
  resources :apartments
  resources :requests
  resources :hotels
  resources :users
  root to: 'apartments#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  before_action :set_administrator, only: %i[ show edit update destroy ]
  before_action :custom_authenticate
  # before_action :authenticate_user!
  # GET /administrators or /administrators.json
  def index
    @administrators = Administrator.all
  end

  # GET /administrators/1 or /administrators/1.json
  def show; end

  # GET /administrators/new
  def new
    @administrator = Administrator.new
  end

  # GET /administrators/1/edit
  def edit; end

  # POST /administrators or /administrators.json
  def create
    @administrator = Administrator.new(administrator_params)

    respond_to do |format|
      if @administrator.save
        format.html { redirect_to administrator_url(@administrator), notice: 'Administrator was successfully created.' }
        format.json { render :show, status: :created, location: @administrator }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administrators/1 or /administrators/1.json
  def update
    respond_to do |format|
      if @administrator.update(administrator_params)
        format.html { redirect_to administrator_url(@administrator), notice: 'Administrator was successfully updated.' }
        format.json { render :show, status: :ok, location: @administrator }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administrators/1 or /administrators/1.json
  def destroy

    respond_to do |format|
      if @administrator.destroy
        format.html { redirect_to hotels_url, notice: 'Administrator was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to hotels_url, notice: 'Something go wrong.' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def custom_authenticate
    authenticate_user!
    if current_user.role != 'Admin'
      head :forbidden
    end
  end

  def set_administrator
    @administrator = Administrator.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def administrator_params
    params.require(:administrator).permit(:email, :name, :surname)
  end
end

app/views/administrators/_form.html.erb
<%= form_with(model: administrator) do |form| %>
  <% if administrator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(administrator.errors.count, "error") %> prohibited this administrator from being saved:</h2>

      <ul>
        <% administrator.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/administrators/edit.html.erb
<h1>Editing Administrator</h1>

<%= render 'form', administrator: @administrator %>

<%= link_to 'Show', @administrator %> |
<%= link_to 'Back', administrators_path %>

app/views/administrators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Administrators</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @administrators.each do |administrator| %>
      <tr>
        <td><%= link_to 'Show', administrator %></td>
        <td><%= link_to 'Edit', edit_administrator_path(administrator) %></td>
        <td><%= link_to 'Destroy', administrator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Administrator', new_administrator_path %>

app/views/administrators/new.html.erb
<h1>New Administrator</h1>

<%= render 'form', administrator: @administrator %>

<%= link_to 'Back', administrators_path %>

app/views/administrators/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_administrator_path(@administrator) %> |
<%= link_to 'Back', administrators_path %>