config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :clients
  devise_for :administrators
  resources :administrators, only: %i[new create destroy show edit update]
  resources :clients, only: %i[new create destroy show edit update]
  resources :bills, only: %i[show create]
  resources :apartments
  resources :requests
  resources :hotels
  resources :users
  root to: 'apartments#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/apartment.rb
class Apartment < ApplicationRecord
  enum apartment_class: %i[A B C Luxe]
  belongs_to :hotel
  has_many :bills
  has_many_attached :images

  monetize :price_cents, as: 'price'
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :room_number, presence: true, numericality: { only_integer: true, greater_than: 0 }, uniqueness: { scope: :hotel_id }

  def apartment_class=(value)
    super
  rescue ArgumentError
    @attributes.write_cast_value('apartment_class', value)
  end

end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  include ApartmentsHelper
  before_action :set_apartment, only: %i[ show edit update destroy ]
  before_action :custom_authenticate, only: %i[ new create edit update destroy ]
  # GET /apartments or apartments.json
  def index
    @apartments = filter_by_params(Apartment.all, filter_params)
    @apartments = sort_by_params(@apartments, sort_params)
  end

  # GET /apartments/1 or /apartments/1.json
  def show; end

  # GET /apartments/new
  def new
    @apartment = Apartment.new
  end

  # GET /apartments/1/edit
  def edit; end

  # POST /apartments or /apartments.json
  def create
    @apartment = Apartment.new(apartment_params)

    respond_to do |format|
      if @apartment.save
        format.html { redirect_to apartment_url(@apartment), notice: 'Apartment was successfully created.' }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1 or /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to apartment_url(@apartment), notice: 'Apartment was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1 or /apartments/1.json
  def destroy
    respond_to do |format|
      if @apartment.destroy
        format.html { redirect_to apartments_url, notice: 'Apartment was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to apartments_url, notice: 'Something go wrong.' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def custom_authenticate
    authenticate_user!
    head :forbidden if current_user.role != 'Admin'
  end

  def filter_params
    params.fetch(:filter, {}).permit(:price_begin, :price_end, hotel: [], apartment_class: [])
  end

  def sort_params
    params.fetch(:sort, {}).permit(:price, :apartment_class)
  end

  def set_apartment
    @apartment = Apartment.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def apartment_params
    params.require(:apartment).permit(:hotel_id, :apartment_class, :room_number, :price, :image)
  end
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
  def filter_by_params(scope, params)
    params.each do |key, value|
      next if value.blank?

      scope = case key.to_s
              when 'apartment_class'
                scope.where(apartment_class: value)
              when 'price_begin'
                scope.where('price_cents>=?', value.to_i * 100)
              when 'price_end'
                scope.where('price_cents<=?', value.to_i * 100)
              when 'hotel'
                scope.where(hotel_id: value)
              else
                scope
              end
    end
    scope
  end

  def sort_by_params(scope, params)
    params.each do |key, value|
      next unless %w[desc asc].include?(value)

      scope = case key.to_s
              when 'price'
                scope.order("price_cents #{value}")
              when 'apartment_class'
                scope.order("apartment_class #{value}")
              else
                scope
              end
    end
    scope
  end
end

app/views/apartments/_form.html.erb
<%= form_with(model: apartment) do |form| %>
  <% if apartment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(apartment.errors.count, "error") %> prohibited this apartment from being saved:</h2>

      <ul>
        <% apartment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/apartments/edit.html.erb
<h1>Editing Apartment</h1>

<%= render 'form', apartment: @apartment %>

<%= link_to 'Show', @apartment %> |
<%= link_to 'Back', apartments_path %>

app/views/apartments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Apartments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apartments.each do |apartment| %>
      <tr>
        <td><%= apartment.id %></td>

        <td><%= apartment.apartment_class %></td>
        <td><%= apartment.price %></td>

        <td><%= apartment.hotel.name %></td>
        <td><%= link_to 'Show', apartment %></td>
        <% if current_user.try(:role) == 'Admin' %>
          <td><%= link_to 'Edit', edit_apartment_path(apartment) %></td>
          <td><%= link_to 'Destroy', apartment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user %>
  <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
  <% else %>
  <%= link_to 'Sing up', new_user_registration_path %>
  <%= link_to 'sing out', new_user_session_path %>

  <% end %>
<%#= link_to 'New Apartment', new_apartment_path %>

app/views/apartments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_apartment_path(@apartment) %> |
<%= link_to 'Back', apartments_path %>